---
title: "plot and save 2"
author: "Robert Hickman"
date: "03/09/2020"
output: html_document
---

```{r libraries, warning=FALSE,message=FALSE}
library(tidyverse)
library(tidymodels)
library(patchwork)
library(gettyR)

```

```{r directories, warning=FALSE,message=FALSE}
dir <- "C:/Users/DHill/Desktop/robert_cell_sorting/sessions"
session <- "U-2020-07-30-s2"

spike_data <- gettyR::open_spike_data(dir, session) 
trace_data <- gettyR::open_cell_trace(dir)

```

```{r}
cells <- unique(unlist(spike_data$sorted_spikes) %>%
           .[grepl("^cell", .)])

create_spike_dirs(session, cells)
```
```{r plot_unsorted_data, warning=FALSE,message=FALSE}
bits <- c("free_reward", "fixation_cross", "win_lose", "fractal_display")
situations <- c(4, 2, 2, 2)

walk2(bits, situations,
      function(b, s) {
        p <- plot_getty_responses(spike_data, s, b)
        path <- paste0(file.path("C:/Users/DHill/Desktop/robert_cell_sorting/sessions", session, "figures/unsorted_responses", b), ".png")
        ggsave(plot = p, filename = path, device = "png")
      })

```


```{r}
p1 <- gettyR::plot_cell_trace(trace_data)
p2 <- gettyR::plot_isi_histogram(spike_data$sorted_spikes)
```

```{r}
plot_and_save_cluster_data <- function(specific_cell, trace_data = trace_data, sorted_spikes = spike_data$sorted_spikes, session) {
  if(is.null(specific_cell)) {
    n_spikes <- do.call(sum, lapply(sorted_spikes, nrow))
  } else {
    n_spikes <- do.call(sum, lapply(sorted_spikes, function(s) nrow(dplyr::filter(s, cell == specific_cell))))
  }
  
  trace_plot <- gettyR::plot_cell_trace(trace_data = trace_data, specific_cell = specific_cell)
  isi_histogram <- gettyR::plot_isi_histogram(spikes = sorted_spikes, specific_cell = specific_cell)
  autocorr_histogram <- gettyR::plot_autocorr(spikes = sorted_spikes, specific_cell = specific_cell)
  pca1 <- gettyR::plot_pca(trace_data = trace_data, specific_cell = specific_cell, xaxis = "PC1", yaxis = "PC2")
  pca2 <- gettyR::plot_pca(trace_data = trace_data, specific_cell = specific_cell, xaxis = "PC1", yaxis = "PC3")
  pca3 <- gettyR::plot_pca(trace_data = trace_data, specific_cell = specific_cell, xaxis = "PC3", yaxis = "PC2")
  
  patchwork <- (trace_plot | isi_histogram | autocorr_histogram) / (pca1 | pca2 | pca3)
  patchwork <- patchwork + 
    plot_annotation(
      title = paste("Sorted cell profile for", specific_cell, "on", session),
      subtitle = paste(n_spikes, "sorted spikes")
    )
  return(patchwork)
}


```

```{r}
cells <- unique(trace_data$cell)

walk(cells, plot_and_save_cluster_data)
```


